kind: wasmer.io/App.v0
name: todo_app_c14
owner: rakeshreddyyerra07
package: .
app_id: da_KWgIvtQU53DA
annotations:
  anybuild.run/provider: "php"
  anybuild.run/config: '{"composer_enable":true,"name":"out","php_public_dir":"public","phpix":true}'
